### ISSUE TITLE
`forge status` and `forge bock` throw error

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/forge-js#314]
```
❯ forge block
ℹ query latest block at 17836
{ type: 'abci_vendor.Version', data: { block: 10, app: 1 } }
/Users/wangshijun/Develop/arcblock/forge-cli/node_modules/@arcblock/forge-message/lib/message.js:187
    throw new Error(`Cannot get fields for type ${type}`);
    ^

Error: Cannot get fields for type abci_vendor.Version
    at formatMessage (/Users/wangshijun/Develop/arcblock/forge-cli/node_modules/@arcblock/forge-message/lib/message.js:187:11)
    at Object.keys.forEach.key (/Users/wangshijun/Develop/arcblock/forge-cli/node_modules/@arcblock/forge-message/lib/message.js:258:21)
    at Array.forEach (<anonymous>)
    at formatMessage (/Users/wangshijun/Develop/arcblock/forge-cli/node_modules/@arcblock/forge-message/lib/message.js:190:23)
    at Object.keys.forEach.key (/Users/wangshijun/Develop/arcblock/forge-cli/node_modules/@arcblock/forge-message/lib/message.js:258:21)
    at Array.forEach (<anonymous>)
    at formatMessage (/Users/wangshijun/Develop/arcblock/forge-cli/node_modules/@arcblock/forge-message/lib/message.js:190:23)
    at Object.value (/Users/wangshijun/Develop/arcblock/forge-cli/node_modules/@arcblock/forge-message/lib/message.js:569:18)
    at displayBlock (/Users/wangshijun/Develop/arcblock/forge-cli/src/cli/block/display/display.js:45:25)
    at EventEmitter.stream.on.d (/Users/wangshijun/Develop/arcblock/forge-cli/src/cli/block/display/display.js:58:24)
```

Caused by some types are removed in vendor proto file.

**Comment by wangshijun** [comment]
cc @PaperHS
