### ISSUE TITLE
我在为用户创建资产时遇到问题

### ISSUE THREAD

**Issue by A-new-b** [ArcBlock/forge-js#476]
我在使用forgejs graphql-client时遇到问题，源代码如下
```js
const GraphqlClient = require('@arcblock/graphql-client');
const { fromRandom } = require('@arcblock/forge-wallet');

const endpoint = process.env.FORGE_API_HOST || 'http://127.0.0.1:8210'; // testnet

const client = new GraphqlClient(`${endpoint}/api`);

(async () => {
try {
    const owner = fromRandom();
    console.log({ owner: owner.toAddress() });

    // 1. declare owner
    let hash = await client.declare({ moniker: 'owner', wallet: owner });
    console.log('declare.owner.result', hash);
    console.log('view owner account', `${endpoint}/node/explorer/accounts/${owner.toAddress()}`);

    // 2. create asset for owner
    let assetAddress;
    [hash, assetAddress] = await client.createAsset({
        moniker: 'asset',
        readonly: false, // if we want to update the asset, we should set this to false
        transferrable: false,
        data: {
            typeUrl: 'json',
            value: {
                key: 'value',
                sn: Math.random(),
            },
        },
        wallet: owner,
    });
    console.log('view asset state', `${endpoint}/node/explorer/assets/${assetAddress}`);
    console.log('create asset tx', `${endpoint}/node/explorer/txs/${hash}`);
} catch (err) {
    console.error(err);
    console.log(JSON.stringify(err.errors));
}
})();

```
这几乎与官方的例子[https://github.com/ArcBlock/forge-js/blob/master/forge/graphql-client/examples/asset.js](url)一样
但却报错
```js
{ owner: 'z1UmpHFEqc8KyJ9TcmTTPQ2qi6fpMqLNgaW' }
declare.owner.result C75B0C3073B87CAD2FECE8900846EE2F609431BA12CB5C9B554DC808FAE952AF
view owner account http://127.0.0.1:8210/node/explorer/accounts/z1UmpHFEqc8KyJ9TcmTTPQ2qi6fpMqLNgaW
{ Error: invalid_sender_state: The sender of this transaction does not exist on this chain.
    at NativeGraphqlClient.client._createResponseError (/home/arcblock/community_server/node_modules/@arcblock/client-extension/lib/index.js:152:21)
    at Promise (/home/arcblock/community_server/node_modules/@arcblock/client-extension/lib/index.js:357:36)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  code: 'invalid_sender_state',
  type: 'create_asset_tx',
  errors:
   [ { locations: [Array],
       message: 'invalid_sender_state',
       path: [Array] } ] }
[{"locations":[{"column":0,"line":2}],"message":"invalid_sender_state","path":["sendTx"]}]

```
这是我本地配置
```
arcblock@iZ2zegctxhllwiiq2srflhZ ~/community_server> forge chain:ls
All Chains:
┌────────────────────┬───────────────┬───────────────┐
│ Name               │ Version       │ Status        │
├────────────────────┼───────────────┼───────────────┤
│ beijing            │ v1.1.1-p0     │ running       │
│ shanghai           │ v1.1.1-p0     │ running       │
└────────────────────┴───────────────┴───────────────┘
arcblock@iZ2zegctxhllwiiq2srflhZ ~/community_server> forge --version
1.3.0

```
这个配置的搭建方法几乎和[https://docs.arcblock.io/zh/handbook/11-forge-cli-in-production/deploy-multi-party-network](url)一样
所以我想知道这大概是什么问题

**Comment by wangshijun** [comment]
@A-new-b https://playground.network.arcblockio.cn/dashboard 以这个 playground 链为例：

- chainId 在界面首页就可以看到，见下面的截图
- chainHost 就是 https://playground.network.arcblockio.cn/api

![image](https://user-images.githubusercontent.com/719985/94643055-875c3e80-0318-11eb-834e-cf5243cbd1c4.png)
